#![cfg(target_os = "macos")]

use super::{ClipboardImage, ClipboardProbe, PasteKind};
use serde::Deserialize;
use std::io::Write;
use std::path::Path;
use std::process::{Command, Stdio};
use std::time::{Duration, Instant};

const JXA_TIMEOUT: Duration = Duration::from_secs(3);

#[derive(Deserialize)]
struct RawProbe {
    #[serde(default, rename = "changeCount")]
    change_count: i64,
    #[serde(default)]
    kind: String,
    #[serde(default)]
    concealed: bool,
    #[serde(default, rename = "fileUrl")]
    file_url: bool,
}

#[derive(Deserialize)]
struct RawImage {
    #[serde(default)]
    width: u32,
    #[serde(default)]
    height: u32,
    #[serde(default)]
    bytes: u64,
    #[serde(default)]
    ok: bool,
}

pub fn probe() -> Option<ClipboardProbe> {
    let out = jxa(PROBE_JS, &[]).ok()?;
    let raw: RawProbe = serde_json::from_str(&out).ok()?;
    let kind = match raw.kind.as_str() {
        "text" => PasteKind::Text,
        "image" => PasteKind::Image,
        _ => PasteKind::None,
    };
    Some(ClipboardProbe {
        change_count: raw.change_count,
        kind,
        concealed: raw.concealed,
        file_url: raw.file_url,
    })
}

pub fn read_image(dest: &Path) -> Option<ClipboardImage> {
    let out = jxa(READ_IMAGE_JS, &[dest.to_str()?]).ok()?;
    let raw: RawImage = serde_json::from_str(&out).ok()?;
    if !raw.ok || raw.width == 0 || raw.height == 0 {
        return None;
    }
    Some(ClipboardImage {
        width: raw.width,
        height: raw.height,
        bytes: raw.bytes,
    })
}

pub fn write_image(src: &Path) -> Result<(), String> {
    let path = src.to_str().ok_or_else(|| "bad path".to_string())?;
    let out = jxa(WRITE_IMAGE_JS, &[path])?;
    if out.trim() == "true" {
        Ok(())
    } else {
        Err("pasteboard write failed".into())
    }
}

fn jxa(source: &str, args: &[&str]) -> Result<String, String> {
    let mut child = Command::new("osascript")
        .args(["-l", "JavaScript", "-"])
        .args(args)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| e.to_string())?;
    if let Some(mut stdin) = child.stdin.take() {
        stdin
            .write_all(source.as_bytes())
            .map_err(|e| e.to_string())?;
    }
    let deadline = Instant::now() + JXA_TIMEOUT;
    loop {
        match child.try_wait() {
            Ok(Some(_)) => break,
            Ok(None) if Instant::now() >= deadline => {
                let _ = child.kill();
                let _ = child.wait();
                return Err("timed out".into());
            }
            Ok(None) => std::thread::sleep(Duration::from_millis(10)),
            Err(e) => return Err(e.to_string()),
        }
    }
    let out = child.wait_with_output().map_err(|e| e.to_string())?;
    if !out.status.success() {
        return Err(String::from_utf8_lossy(&out.stderr).trim().to_string());
    }
    Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

const PROBE_JS: &str = r#"
function run() {
  ObjC.import('AppKit');
  var pb = $.NSPasteboard.generalPasteboard;
  var types = ObjC.deepUnwrap(pb.types) || [];
  var fileUrl = types.indexOf('public.file-url') >= 0
    || types.indexOf('NSFilenamesPboardType') >= 0
    || types.indexOf('com.apple.pasteboard.promised-file-url') >= 0;
  var kind = 'none';
  if (types.indexOf('public.png') >= 0 || types.indexOf('public.tiff') >= 0) {
    kind = 'image';
  } else if (types.indexOf('public.utf8-plain-text') >= 0 || types.indexOf('public.text') >= 0) {
    kind = 'text';
  }
  var concealed = types.indexOf('org.nspasteboard.ConcealedType') >= 0
    || types.indexOf('org.nspasteboard.TransientType') >= 0
    || types.indexOf('org.nspasteboard.AutoGeneratedType') >= 0;
  return JSON.stringify({
    changeCount: Number(pb.changeCount),
    kind: kind,
    concealed: concealed,
    fileUrl: fileUrl
  });
}
"#;

const READ_IMAGE_JS: &str = r#"
function run(argv) {
  ObjC.import('AppKit');
  var pb = $.NSPasteboard.generalPasteboard;
  var data = pb.dataForType($.NSPasteboardTypePNG);
  if (!data || !data.js) {
    var tiff = pb.dataForType($.NSPasteboardTypeTIFF);
    if (!tiff || !tiff.js) return JSON.stringify({ ok: false });
    var conv = $.NSBitmapImageRep.imageRepWithData(tiff);
    if (!conv || !conv.js) return JSON.stringify({ ok: false });
    data = conv.representationUsingTypeProperties($.NSBitmapImageFileTypePNG, $());
  }
  if (!data || !data.js) return JSON.stringify({ ok: false });
  var rep = $.NSBitmapImageRep.imageRepWithData(data);
  var w = 0, h = 0;
  if (rep && rep.js) { w = Number(rep.pixelsWide); h = Number(rep.pixelsHigh); }
  var ok = data.writeToFileAtomically(argv[0], true);
  return JSON.stringify({ ok: ok, width: w, height: h, bytes: Number(data.length) });
}
"#;

const WRITE_IMAGE_JS: &str = r#"
function run(argv) {
  ObjC.import('AppKit');
  var data = $.NSData.dataWithContentsOfFile(argv[0]);
  if (!data || !data.js) return 'false';
  var pb = $.NSPasteboard.generalPasteboard;
  pb.clearContents;
  return pb.setDataForType(data, $.NSPasteboardTypePNG) ? 'true' : 'false';
}
"#;

#[cfg(test)]
mod tests {
    use super::{probe, read_image, write_image};
    use crate::os::PasteKind;

    #[test]
    #[ignore]
    fn image_round_trip() {
        let dir = std::env::temp_dir().join(format!("caddie-pb-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();
        let src = dir.join("in.png");
        std::fs::write(&src, png_64x64()).unwrap();

        write_image(&src).expect("write to pasteboard");

        let p = probe().expect("probe");
        assert_eq!(p.kind, PasteKind::Image);
        assert!(!p.concealed);
        assert!(!p.file_url);

        let dest = dir.join("out.png");
        let meta = read_image(&dest).expect("read from pasteboard");
        assert_eq!((meta.width, meta.height), (64, 64));
        assert!(dest.exists());
        assert!(meta.bytes > 0);

        let _ = std::fs::remove_dir_all(&dir);
    }

    fn png_64x64() -> Vec<u8> {

        let mut raw = Vec::new();
        for _ in 0..64 {
            raw.push(0u8);
            raw.extend(std::iter::repeat_n([32u8, 96, 200], 64).flatten());
        }
        let mut out = b"\x89PNG\r\n\x1a\n".to_vec();
        let mut ihdr = 64u32.to_be_bytes().to_vec();
        ihdr.extend(64u32.to_be_bytes());
        ihdr.extend([8, 2, 0, 0, 0]);
        push_chunk(&mut out, b"IHDR", &ihdr);
        push_chunk(&mut out, b"IDAT", &zlib_stored(&raw));
        push_chunk(&mut out, b"IEND", &[]);
        out
    }

    fn push_chunk(out: &mut Vec<u8>, tag: &[u8; 4], data: &[u8]) {
        out.extend((data.len() as u32).to_be_bytes());
        let mut body = tag.to_vec();
        body.extend(data);
        out.extend(&body);
        out.extend(crc32(&body).to_be_bytes());
    }

    fn zlib_stored(data: &[u8]) -> Vec<u8> {
        let mut out = vec![0x78, 0x01];
        for (i, block) in data.chunks(65535).enumerate() {
            let last = u8::from((i + 1) * 65535 >= data.len());
            out.push(last);
            out.extend((block.len() as u16).to_le_bytes());
            out.extend((!(block.len() as u16)).to_le_bytes());
            out.extend(block);
        }
        out.extend(adler32(data).to_be_bytes());
        out
    }

    fn crc32(data: &[u8]) -> u32 {
        let mut crc = 0xffff_ffffu32;
        for byte in data {
            crc ^= u32::from(*byte);
            for _ in 0..8 {
                crc = if crc & 1 == 1 {
                    (crc >> 1) ^ 0xedb8_8320
                } else {
                    crc >> 1
                };
            }
        }
        !crc
    }

    fn adler32(data: &[u8]) -> u32 {
        let (mut a, mut b) = (1u32, 0u32);
        for byte in data {
            a = (a + u32::from(*byte)) % 65521;
            b = (b + a) % 65521;
        }
        (b << 16) | a
    }
}
